apiVersion: v1
kind: Service
metadata:
  name: invoicing-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: invoicing-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32112
  selector:
    app: invoicing-deployment