apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicing-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoicing-deployment
  template:
    metadata:
      labels:
        app: invoicing-deployment
    spec:
      containers:
        - name: invoicing-deployment
          image: 'danielmigchels/invoicing:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: invoicing-secret