apiVersion: v1
kind: Secret
metadata:
  name: invoicing-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ConnectionStrings__Postgres: {{ .Values.connectionstrings.postgres | b64enc }}