apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
data:
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.username }}